name: 'Build Multi-Arch Docker Image'
description: 'Builds a multi-architecture (amd64, arm64) Docker image and optionally pushes it to a registry.'

inputs:
  tags:
    description: 'The Docker image tags (comma or newline separated)'
    required: true
  push:
    description: 'Whether to push the image to the registry'
    required: false
    default: 'false'
  registry_username:
    description: 'Username for the container registry'
    required: false
  registry_password:
    description: 'Password/token for the container registry'
    required: false
  registry:
    description: 'The container registry'
    required: false
    default: 'ghcr.io'
  platforms:
    description: 'Target platforms for the build (comma-separated)'
    required: false
    default: 'linux/amd64,linux/arm64'

runs:
  using: "composite"
  steps:
    - name: Set up QEMU for multi-arch builds
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Registry
      if: ${{ inputs.push == 'true' }}
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.registry_username }}
        password: ${{ inputs.registry_password }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        platforms: ${{ inputs.platforms }}
        tags: ${{ inputs.tags }}
        push: ${{ inputs.push }}
        # Add caching to speed up builds
        cache-from: type=gha
        cache-to: type=gha,mode=max
