name: Helm Build

on:
  push:
    branches:
    - '**'
    paths:
    - 'deploy/**'
  pull_request:
    branches:
    - '**'
    paths:
    - 'desec/**'
    - 'go.*'
    - '*.go'
    - 'Dockerfile'
  workflow_dispatch:


jobs:
  build-chart:
    name: Build chart
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Set up Helm
      uses: azure/setup-helm@v4
      with:
        version: v3.13.0 # Specify a specific Helm version

    - name: Helm linter
      run: |
        helm lint deploy/**

    - name: Build helm package
      run: |
        helm package deploy/**
